{% set version = "6.2.0" %}

{% set PYTHON = PTYHON | default("$PYTHON") %}

package:
  name: bleach
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/bleach/bleach-{{ version }}.tar.gz
  sha256: 123e894118b8a599fd80d3ec1a6d4cc7ce4e5882b1317a7e1ba69b56e95f991f

build:
  number: 2
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - webencodings
  run_constrained:
    - tinycss2 >=1.1.0,<1.5
test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - bleach

outputs:
  - name: bleach

  - name: bleach-with-css
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("bleach", exact=True) }}
    test:
      requires:
        - pip
        - python {{ python_min }}
      commands:
        - pip check
    about:
      summary: Easy, whitelist-based HTML-sanitizing tool (with [css])

about:
  home: https://github.com/mozilla/bleach
  license: Apache-2.0
  license_family: Apache
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE
    - bleach/_vendor/html5lib-1.1.dist-info/LICENSE
  summary: Easy, whitelist-based HTML-sanitizing tool
  description: |
    Bleach is an allowed-list-based HTML sanitizing library that escapes or
    strips markup and attributes.
  dev_url: https://github.com/mozilla/bleach
  doc_url: https://bleach.readthedocs.io/
  doc_source_url: https://github.com/mozilla/bleach/blob/master/docs/index.rst

extra:
  feedstock-name: bleach
  recipe-maintainers:
    - minrk
    - ocefpaf
