{% set name = "bleach" %}
{% set version = "2.0.0" %}
{% set sha256 = "b9522130003e4caedf4f00a39c120a906dcd4242329c1c8f621f5370203cbc30" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - html5lib >=0.99999999
    - six

test:
  imports:
    - bleach

about:
  home: https://github.com/mozilla/bleach
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Bleach is a whitelist-based HTML sanitizing library that escapes or strips markup and attributes.

  dev_url: https://github.com/mozilla/bleach
  doc_url: https://bleach.readthedocs.io/

extra:
  recipe-maintainers:
    - minrk
