context:
  name: bleach
  version: 6.2.0

recipe:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/b/bleach/bleach-${{ version }}.tar.gz
  sha256: 123e894118b8a599fd80d3ec1a6d4cc7ce4e5882b1317a7e1ba69b56e95f991f

build:
  number: 3

outputs:
  - package:
      name: ${{ name }}
    build:
      number: 3
      noarch: python
      script:
        - python -m pip install . -vv
    requirements:
      host:
        - pip
        - python ${{ python_min }}.*
        - setuptools
      run:
        - python >=${{ python_min }}
        - webencodings
      run_constraints:
        - tinycss >=1.1.0,<1.5
    tests:
      - python:
          pip_check: true
          python_version: ${{ python_min }}
          imports:
            - bleach
  - package:
      name: ${{ name }}-with-css
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage(name, exact=true) }}
        # version is pinned in bleach
        - tinycss2
    tests:
      - python:
          imports: bleach
          python_version: ${{ python_min }}
          pip_check: true
    about:
      summary: Easy, whitelist-based HTML-sanitizing tool (with [css])

about:
  homepage: https://github.com/mozilla/bleach
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE
    - bleach/_vendor/html5lib-1.1.dist-info/LICENSE
  summary: Easy, whitelist-based HTML-sanitizing tool
  description: |
    Bleach is an allowed-list-based HTML sanitizing library that escapes or
    strips markup and attributes.
  repository: https://github.com/mozilla/bleach
  documentation: https://bleach.readthedocs.io/

extra:
  feedstock-name: bleach
  recipe-maintainers:
    - minrk
    - ocefpaf
